### PR TITLE
Load types installed at runtime

### LINKED ISSUE #938: A node red restart is necessary after installing third party ui nodes
### Current Behavior

If a non-core node such as @flowfuse/node-red-dashboard-2-ui-led is installed then it is necessary to restart node-red in order for the widget to appear on the dashboard. Before the restart the widget appears just as an empty space on the page. It seems that this is also the case for ui-frame and ui-gauge-classic.

### Expected Behavior

Either a restart should not be required, or the user should be informed that a restart is required.

### Steps To Reproduce

_No response_

### Environment

- Dashboard version: 1.11.1
- Node-RED version: 4.0.0 beta 4
- Node.js version: 20.5.1
- npm version:
- Platform/OS:
- Browser: Edge

### Have you provided an initial effort estimate for this issue?

I am not a FlowFuse team member

### PR DESCRIPTION
**Pull request by Steve-Mcl**
closes #938

## Description

Load widget type info upon `type-registered` event to remove the need to restart node-red after a contrib node is installed at runtime.

### Demo

https://github.com/user-attachments/assets/726907c6-c597-4de0-ad31-f3740b3f97b0

## Related Issue(s)
#938

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

File: nodes/config/ui_base.js [hunk 1]
```diff
@@ -188,6 +190,20 @@ module.exports = function (RED) {
         }
     }
 
+    function onTypeRegistered (node, type) {
+        // reload nodes from user directory package.json
+        if (RED.settings?.userDir) {
+            try {
+                const contribs = getThirdPartyWidgets(RED.settings.userDir)
```
Comment (joepavitt) [inline nodes/config/ui_base.js:197]: Does this not restrict such that https://github.com/FlowFuse/node-red-dashboard/pull/1286/files would not work anymore?

**Review by joepavitt — APPROVED** [review]
