### PR TITLE
Navigation: Collapse sidebar after navigating to a new page, if configured

### LINKED ISSUE #727: Navigation Bar does not collapse after page change
### Current Behavior

Navigation Bar does not collapse after a new page was selected.

### Expected Behavior

Navigation Bar does collapse after a new page was selected.

### Steps To Reproduce

Set the `Style` of `ui-base` to `Collapsing`.

### Environment

- Dashboard version: 1.6.1
- Node-RED version: 4.0.0 beta1
- Node.js version:
- npm version:
- Platform/OS: Raspberry OS
- Browser: Firefox / Ubuntu

### Have you provided an initial effort estimate for this issue?

I am not a FlowFuse team member

### PR DESCRIPTION
**Pull request by joepavitt**
## Description

- re-collapses the collapsable side bar when a new page is navigated to

Closes #727 

### After:

https://github.com/FlowFuse/node-red-dashboard/assets/99246719/549d4b1b-31c6-44c7-87ed-77a703383e76

### CODE REVIEW

File: ui/src/layouts/Baseline.vue [hunk 1]
```diff
@@ -209,6 +210,15 @@ export default {
             } else {
                 this.drawer = !this.drawer
             }
+        },
+        selectPage (page) {
+            console.log(this.navigationStyle)
+            if (this.navigationStyle === 'default') {
+                this.drawer = false
+            }
+            // this.$router.push({
```
Comment (cstns) [inline ui/src/layouts/Baseline.vue:219]: we should also remove commented out code

File: ui/src/layouts/Baseline.vue [hunk 2]
```diff
@@ -209,6 +210,15 @@ export default {
             } else {
                 this.drawer = !this.drawer
             }
+        },
+        selectPage (page) {
```
Comment (cstns) [inline ui/src/layouts/Baseline.vue:214]: A key practice I've adopted is prefixing event listener method names with 'on'. This makes their role clear and enhances code readability.

**Review by cstns — CHANGES_REQUESTED** [review]
Looks good to me! Some suggestions on cleaning some leftovers, nothing critical

**Review by cstns — APPROVED** [review]

**Comment by cstns** [comment]
There are some failing e2e tests but don't seem to be related to this PR
