### PR TITLE
Sidebar: Ensure "Fixed" layout adapts to mobile view

### LINKED ISSUE #1674: Sidebar "Fixed" mode does not fall back to "Appear over content" on mobile
### Current Behavior

According to the official documentation, when the Sidebar Style is set to Fixed, it should remain visible on desktop but automatically switch to "Appear over content" on mobile (below 768px width).
This behavior does not happen — the sidebar stays permanently visible, even on small screens.

### Expected Behavior

The sidebar should automatically switch to "Appear over content" behavior on screens smaller than 768px when Fixed is selected.

### Steps To Reproduce

Install a fresh instance of Node-RED with @flowfuse/node-red-dashboard
Set the Sidebar Style in ui-base to Fixed
Deploy and open the dashboard on a mobile device or using Chrome DevTools responsive view (e.g. iPhone 8)
Observe that the sidebar does not collapse or float over content, even if window.innerWidth is < 768

### Environment

Node-RED v3.1.9 with latest @flowfuse/node-red-dashboard
Tested on Chrome, Firefox
Tested with clean configuration, no custom CSS or JS

### Have you provided an initial effort estimate for this issue?

I am not a FlowFuse team member

### PR DESCRIPTION
**Pull request by joepavitt**
## Description

- Changes the layout style for mobile if "Fixed" is set. At 768 pixels (standard "mobile" breakpoint), we now remove the fixed sidebar and revert to the "Appears over Content" as per our documentation

## Related Issue(s)

Closes #1674

### CODE REVIEW

File: ui/src/layouts/Baseline.vue [hunk 1]
```diff
@@ -269,8 +277,16 @@ export default {
...
         this.updateTheme()
+        this.checkMobile()
+        window.addEventListener('resize', this.checkMobile)
+    },
+    beforeUnmount () {
+        window.removeEventListener('resize', this.checkMobile)
     },
     methods: {
+        checkMobile () {
+            this.isMobile = window.innerWidth < 768
```
Comment (Steve-Mcl) [inline ui/src/layouts/Baseline.vue:288]: Magic number is somewhat arbitrary and not conducive to being "mobile"

What is the logic here? Is it just that the screen is sufficiently small (regardless of being mobile) to trigger this logic?

Comment (joepavitt) [reply ui/src/layouts/Baseline.vue:288]: > What is the logic here? Is it just that the screen is sufficiently small (regardless of being mobile) to trigger this logic?

Yes, "is mobile" isn't really the right term, more "is small", but its a breakpoint that's synonymous with mobile.
