### PR TITLE
Missing data after reconnect

### LINKED ISSUE #1297: Chart node missing data after page reconnect
### Current Behavior

When you have an open browser tab showing chart in background, after some time the page disconnects. When returning to tab the page reconnect, and does not refresh. When new data comes in the data for the time the page was not connected is missing, It returns after you refresh page.
images available here https://discourse.nodered.org/t/dashboard-2-0-chart-node-page-reconnect-issue/91017

### Expected Behavior

When page reconnects the page should be refreshed to show the missing data

### Steps To Reproduce

create chart feed in data every 10 seconds. send tab to background. wait 20mins, return to tab and wait for new incoming data

### Environment

- Dashboard version: 1.16
- Node-RED version: 3.1.3
- Node.js version: 20
- npm version: 5
- Platform/OS: Android
- Browser: chrome

### Have you provided an initial effort estimate for this issue?

I am not a FlowFuse team member

### PR DESCRIPTION
**Pull request by Steve-Mcl**
closes #1297

## Description

Watches for re-connection in the data tracker and re-sends `widget-load` upon detecting reconnection.

NOTE: I found a bug in current dashboard that multiplies the handlers everytime a different page is visitied.  This Pr completely refactors the event hook up so that ALL (and only the widgets associated handlers) are properly and always cleaned up. 

### Demo
O1Oj5dnMmq

## Related Issue(s)

 #1297
## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

**Comment by Steve-Mcl** [comment]
Some good news. @colinl has tried this out against related issues & confirmed it

https://github.com/FlowFuse/node-red-dashboard/issues/1297#issuecomment-2381352730

**Comment by colinl** [comment]
In fact I meant to post that here rather than against the issue.

File: ui/src/widgets/data-tracker.mjs [hunk 1]
```diff
@@ -45,55 +47,88 @@ export function useDataTracker (widgetId, onInput, onLoad, onDynamicProperties)
         }
     }
 
+    function onWidgetLoad (msg, state) {
+        // console.log('widget-load::msg-input:' + widgetId, msg, state)
```
Comment (joepavitt) [inline ui/src/widgets/data-tracker.mjs:51]:
```suggestion
```

File: ui/src/widgets/data-tracker.mjs [hunk 2]
```diff
@@ -45,55 +47,88 @@ export function useDataTracker (widgetId, onInput, onLoad, onDynamicProperties)
...
+                store.commit('data/bind', {
+                    widgetId,
+                    msg
+                })
+            }
+        }
+    }
+
+    function onMsgInput (msg) {
+        // console.log('data-tracker::msg-input:' + widgetId, msg)
```
Comment (joepavitt) [inline ui/src/widgets/data-tracker.mjs:73]:
```suggestion
```

File: ui/src/widgets/data-tracker.mjs [hunk 3]
```diff
@@ -45,55 +47,88 @@ export function useDataTracker (widgetId, onInput, onLoad, onDynamicProperties)
...
+
+    function onDisconnect () {
+        console.log('socket disconnect detected in data-tracker, setting doReconnectSendWidgetLoad to true')
+        // To get a disconnect, we must have previously been connected.
+        // Set flag to inform onConnect to emit widget-load
+        emitWidgetLoadOnConnect = true
+    }
+
+    function onConnect () {
+        console.log('socket connect detected in data-tracker' + (emitWidgetLoadOnConnect ? ', emitting widget-load' : ''))
```
Comment (joepavitt) [inline ui/src/widgets/data-tracker.mjs:100]:
```suggestion
```

File: ui/src/widgets/data-tracker.mjs [hunk 4]
```diff
@@ -45,55 +47,88 @@ export function useDataTracker (widgetId, onInput, onLoad, onDynamicProperties)
...
+                msg // TODO: we should sanitise what is stored in the store?
+                // One way to do this is to permit only keys explicitly listed in the widget's config (default to topic+payload if none are specified)
+                // A smarter? way to do this is to scan the template for msg.? binds and store only those keys
+                // For now, we'll just store the whole msg
+            })
+        }
+    }
+
+    function onDisconnect () {
+        console.log('socket disconnect detected in data-tracker, setting doReconnectSendWidgetLoad to true')
```
Comment (joepavitt) [inline ui/src/widgets/data-tracker.mjs:93]:
```suggestion
```

**Review by joepavitt — CHANGES_REQUESTED** [review]

File: ui/src/widgets/data-tracker.mjs [hunk 5]
```diff
@@ -45,55 +47,84 @@ export function useDataTracker (widgetId, onInput, onLoad, onDynamicProperties)
...
+    }
+
+    function onDisconnect () {
+        // To get a disconnect, we must have previously been connected.
+        // Set flag to inform onConnect to emit widget-load
+        emitWidgetLoadOnConnect = true
+    }
+
+    function onConnect () {
+        if (emitWidgetLoadOnConnect) {
```
Comment (joepavitt) [inline ui/src/widgets/data-tracker.mjs:97]:
```suggestion
        // when we unexpectedly disconnect, this is set to true
        if (emitWidgetLoadOnConnect) {
```

**Review by joepavitt — APPROVED** [review]
Added a single line comment just as it took me a few reads to follow, but this is great. Thanks @Steve-Mcl
