### PR TITLE
Layouts: Ensure we're parsing float on the "px" row height

### LINKED ISSUE #1215: Apparent layout change on small screens since 1.14.0
### Current Behavior

I am not sure if this is a regression or an intended change.  I have a page with Layout Fixed and Theme Sizings settings:

image

Using version 1.14.0 of the dashboard, in a small window, and on a tablet, with three groups each 3 wide, it looks like 

Screenshot from 2024-08-17 08-48-51

but with the current `main` branch (16th Aug 2024), in the same window size, it only shows two groups across, pushing the third off the screen.

image

Is this an intended change, and if it is how do I restore the previous functionality please?

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Environment

- Dashboard version: Current main branch, commit cd5d1ce42a
- Node-RED version: 4.0.2
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

### Have you provided an initial effort estimate for this issue?

I am not a FlowFuse team member

### PR DESCRIPTION
**Pull request by joepavitt**
## Description

When reconciling the `rowHeight` into the CSS vars, made an error on Fixed layouts which meant that the `48px` was then included ins a JS calculation for the width, failing (because of the inclusion of `px`) and then not setting the width properly.

This PR ensures that `rowHeight` is a number, before injecting it into the width calculations.

## Related Issue(s)

Fixes #1215

### CODE REVIEW

File: ui/src/layouts/Group.vue [hunk 1]
```diff
@@ -30,6 +30,7 @@ export default {
     },
     computed: {
         columns () {
+            console.log(this.group.width)
```
Comment (Steve-Mcl) [inline ui/src/layouts/Group.vue:33]:
```suggestion
```

**Review by Steve-Mcl — APPROVED** [review]
Approved with suggestion

File: ui/src/layouts/Group.vue (hunk 1 above)
Comment (gayanSandamal) [reply ui/src/layouts/Group.vue]: Fixed the above as Joe is not available today

**Review by gayanSandamal — APPROVED** [review]
Removed the console statement as Joe is not available today.

Looks good to me.
