### PR TITLE
Use an HTTPS Agent and HTTPS scheme if RED.settings.https is set

### LINKED ISSUE #1473: 500 error when layout editor attempts to save changes
### Current Behavior

Open Layout Editor, make changes to layout and attempt to save results in a error 500, and changes not saved.

dash

and developer console...

error

### Expected Behavior

Open Layout Editor, make changes to layout and select save. The changes should then be saved.

### Steps To Reproduce

As above

### Environment

- Dashboard version: 1.19.1
- Node-RED version: 4.0.5
- Node.js version: 20.16
- npm version: 10.8.1
- Platform/OS: Oracle remote cloud server / Canonical-Ubuntu-22.04-aarch64-2023.02.15-0
- Browser: Chrome Version 130.0.6723.119

### Have you provided an initial effort estimate for this issue?

I am not a FlowFuse team member

### PR DESCRIPTION
**Pull request by Steve-Mcl**
fixes #1473

## Description

Supersedes https://github.com/FlowFuse/node-red-dashboard/pull/1480

- Checks `RED.settings.https` is "something" and if yes:
   - switches the URL scheme to "https://"
   - Adds an HTTPS `Agent` & spreads whatever is in `RED.settings.https` into the Agent (permitting any extras to be included or to override the default `rejectUnauthorized: false` if so desired) 

### NOTE:

I have tested a variation of this code on a users VM (thanks for the support @Paul-Reed)
By variation, I mean an older branch but the relevant parts of this PR were used and verified.

## Related Issue(s)

#1473

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

File: nodes/config/ui_base.js [hunk 1]
```diff
@@ -1130,7 +1131,17 @@ module.exports = function (RED) {
         const host = RED.settings.uiHost
         const port = RED.settings.uiPort
         const httpAdminRoot = RED.settings.httpAdminRoot
-        const url = 'http://' + (`${host}:${port}/${httpAdminRoot}flows`).replace('//', '/')
+        let scheme = 'http://'
+        let httpsAgent
+        if (RED.settings.https) {
+            const https = (typeof RED.settings.https === 'function' ? RED.settings.https() : RED.settings.https) || {}
```
Comment (knolleary) [inline nodes/config/ui_base.js:1137]: If `RED.settings.https` is a function, then it *might* return a promise that needs to be resolved first. Here's how the core handles it:

https://github.com/node-red/node-red/blob/master/packages/node_modules/node-red/red.js#L243

Comment (Steve-Mcl) [reply nodes/config/ui_base.js]: thanks Nick. resolved in [1771bbe](https://github.com/FlowFuse/node-red-dashboard/pull/1488/commits/1771bbe77e72a8f5cb52fa0e3abaf700413d3e9c)

**Review by knolleary — APPROVED** [review]

**Comment by joepavitt** [comment]
Oddly keep getting 2 x slider tests failing, but I see no reason as to why that would be caused by this.

**Comment by Steve-Mcl** [comment]
> Oddly keep getting 2 x slider tests failing, but I see no reason as to why that would be caused by this.

This is (deliberately) based of the newer WYSIWYG work since it fixed something in this area and I didnt want to do the work twice.

In theory, the problem lies in the base branch (not this)

Investigating base branch [widget-wysiwyg](https://github.com/FlowFuse/node-red-dashboard/tree/widget-wysiwyg)
