### PR TITLE
Handle trailing slashes in the URL

### LINKED ISSUE #1476: URL with trailing "/"
### Current Behavior

"www.example.com/dashboard/mypage"  works but "www.example.com/dashboard/mypage/" does not work.

When nginx is used as a reverse proxy, it adds a trailing "/" , I imagine that the trailing "/" could be an issue with other configurations.

### Expected Behavior

Ignore trailing "/".

### Steps To Reproduce

_No response_

### Environment

- Dashboard version:  1.19.1
- Node-RED version: 4.0.5: Maintenance Release Editor
- Node.js version:
- npm version:
- Platform/OS: Linux
- Browser: FireFox 132.0.2 (64-bit)

### Have you provided an initial effort estimate for this issue?

I can not provide an initial effort estimate

### PR DESCRIPTION
**Pull request by Steve-Mcl**
closes #1476

## Description

After some consideration, we will stick with slash-less URLs like /page1, and enforce that style with a 301 redirect middleware. 
It’s cleaner, SEO-friendly, backward-compatible, and avoids unnecessary rewrites.

## Related Issue(s)

#1476

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [x] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

**Comment by Steve-Mcl** [comment]
@robertsLando @Bond246 @rsp92028 
Would the changes in this PR satisfy your issue?


The important part of the change is here: 
https://github.com/FlowFuse/node-red-dashboard/pull/1663/files#diff-76241199d5a97f1b00433a720ea273842ca6515d31015b1b24aee147e2a975bdR137-R143


In effect, what it does is:

1. It checks if someone is trying to open a page with with a `/` at the end
2. It then redirects (with a 301 status) to the correct page without the trailing slash.

File: nodes/config/ui_base.js [hunk 1]
```diff
@@ -126,6 +126,23 @@ module.exports = function (RED) {
...
+                    return
+                }
+
+                if (req.path.slice(-1) === '/' && req.path.length > 1) {
+                    const query = req.url.slice(req.path.length)
+                    const safePath = req.path.slice(0, -1).replace(/\/+/g, '/')
+                    res.redirect(301, safePath + query)
+                } else {
+                    next()
+                }
```
Comment (robertsLando) [inline nodes/config/ui_base.js:143]: I suggest to add a comment here mentioning the underlying issue that this fixes as it's not easy to remember the logic that requires this :)

**Review by robertsLando — APPROVED** [review]
Didn't tested this on my end but code side looks good

File: nodes/config/ui_base.js (hunk 1 above)
Comment (joepavitt) [reply nodes/config/ui_base.js:143]: Agree with adding a comment here, otherwise, this looks good to go

Comment (joepavitt) [reply nodes/config/ui_base.js:143]: @Steve-Mcl can you action this please? Then we can get a new Dashboard release out.

Comment (Steve-Mcl) [reply nodes/config/ui_base.js]: Done Joe.

**Review by joepavitt — APPROVED** [review]

**Comment by dceejay** [comment]
@Steve-Mcl @joepavitt - please see this thread - https://discourse.nodered.org/t/flowfuse-dashboard-2-0-issue-err-too-many-redirects/97107/6

I also saw this too_many_redirects loop when using my worldmap node (which sets up it's own endpoint also) but never figured out why...

**Comment by dceejay** [comment]
Hi - I was using it within an iframe so should was just set to /worldmap - but on one instance it went into that loop and wouldn't come out.. See also https://discourse.nodered.org/t/worldmap-dashboard-2-0-iframe-example-error-too-many-redirects/97123 for another user with same issue

**Comment by Bond246** [comment]
For me the problem still exists.
I use traefik reverse  proxy with an "addprefix" middleware that redirects the base-path "/" to "/dashboard/some-page". 
Before the 1.24er dashboard-version there was just a problem with trailing slashes and traefik said it can't reach `/dashboard/some-page/`. 

Now with the new version the browser-path is updated to `/dashboard/some-page` and traefik try to reach `/dashboard/some-page/dashboard/some-page`... obviously not working...

**Comment by Steve-Mcl** [comment]
@Bond246 is this not an issue with your setup? 

You state that **"addprefix" middleware that redirects the base-path "/" to "/dashboard/some-page".** so why would your configuration be appending "dashboard/some-page" to "dashboard/some-page"?

All the fix in this PR does is to redirect (with a 302 status code) from `/dashboard/xxx/` to `/dashboard/xxx` (the redirect from `dashboard/` to `dashboard/first-page` was an existing feature)

**Comment by Steve-Mcl** [comment]
@Bond246 could you share your traefik config (sanitise where necessary).

**Comment by Steve-Mcl** [comment]
@Bond246 I am not up to speed on traefik but 

You currently have two middlewares:
* nodered-dashboard-page1: adds prefix /dashboard/page1
* nodered-dashboard-page2: adds prefix /dashboard/page2

BUT:
* They just add a prefix → e.g., `/` becomes `/dashboard/page1`,
* they don’t check the incoming path — they will blindly apply the prefix even if the request is already under `/dashboard/page1`.


This is why you’re seeing things like:

```
/dashboard/page1 → /dashboard/page1/dashboard/page1 → /dashboard/page1/dashboard/page1/dashboard/page1 ...
```

You could try Redirect only:
* `/`
* `/dashboard`
* `/dashboard/`

But leave:
* `/dashboard/page1`
* `/dashboard/page2`
* anything under `/dashboard/*`
untouched.


Something like:
```
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: nodered-dashboard-redirect
  namespace: nodered
spec:
  redirectRegex:
    regex: ^(/dashboard)?/?$
    replacement: /dashboard/page1
    permanent: true
```


---

Why I suspect `addPrefix` is not right here: `addPrefix` always prepends the string, no matter what the incoming path is. AFAIK, it doesn’t check if the path already has it so can lead to repeated prefixes. I _think_ by switching to `redirectRegex`, you can conditionally match and rewrite only when necessary?

**Comment by Bond246** [comment]
@Steve-Mcl you are correct, addPrefix always would add the path even if it already exists.
But i also could got to google.com/foo/bar and would get 404 becaus it doesn't exist. So in my case the user doesn't know and doesn't have to know that there is something like /dashboard/xyz because he stays in his single specific space under /dashboard/page1 and thats it. Everything he needs is there.

But i will try to test redirectRegex which in this case would make the path that is added visible. Not so nice in my opinion like addPrefix but would fix the issue.

**Comment by Bond246** [comment]
`redirectRegex` worked well like it should.
Not so nice like `addprefix` where the path was not provided to the browser url-bar but ok for what i want to do with it.
