### PR TITLE
Ensure we are deep-cloning objects in our datastore, and prevent memory overlap

### LINKED ISSUE #692: Incorrect data stored when msg.payload is modified downstream
### Current Behavior

Modifications to `msg` after a Dashboard node has emitted it are reflected within the attached Dashboard node. This means that on refresh, the loaded `msg` is inaccurate from that emitted by the node. 

This causes widgets like the `ui-switch` to not be able to load their state anymore.

### Simple flow to modify `msg.payload`

Screenshot 2024-03-20 at 16 33 14

### The value in the store for this widget:

Screenshot 2024-03-20 at 16 32 44

### Expected Behavior

All nodes should store the latest message they emitted, and the state should reflect the value at emission, not the modified version further down the flow.

### Steps To Reproduce
<details>
  <summary>flow.json</summary>
  ```json
  [
      {
          "id": "d1b4c176152f1d83",
          "type": "ui-switch",
          "z": "bb1b48cecdd8e583",
          "name": "",
          "label": "switch",
          "group": "c9d5f2f2ee03be37",
          "order": 0,
          "width": 0,
          "height": 0,
          "passthru": false,
          "topic": "topic",
          "topicType": "msg",
          "style": "",
          "className": "",
          "onvalue": "true",
          "onvalueType": "bool",
          "onicon": "",
          "oncolor": "",
          "offvalue": "false",
          "offvalueType": "bool",
          "officon": "",
          "offcolor": "",
          "x": 270,
          "y": 360,
          "wires": [
              [
                  "2b24509643b7c523"
              ]
          ]
      },
      {
          "id": "4ed934f9ceaa0800",
          "type": "debug",
          "z": "bb1b48cecdd8e583",
          "name": "debug 7",
          "active": true,
          "tosidebar": true,
          "console": false,
          "tostatus": false,
          "complete": "false",
          "statusVal": "",
          "statusType": "auto",
          "x": 620,
          "y": 360,
          "wires": []
      },
      {
          "id": "2b24509643b7c523",
          "type": "change",
          "z": "bb1b48cecdd8e583",
          "name": "",
          "rules": [
              {
                  "t": "set",
                  "p": "payload",
                  "pt": "msg",
                  "to": "Override",
                  "tot": "str"
              }
          ],
          "action": "",
          "property": "",
          "from": "",
          "to": "",
          "reg": false,
          "x": 440,
          "y": 360,
          "wires": [
              [
                  "4ed934f9ceaa0800"
              ]
          ]
      },
      {
          "id": "c9d5f2f2ee03be37",
          "type": "ui-group",
          "name": "GH API Tests",
          "page": "b32a72f75a638968",
          "width": "12",
          "height": "1",
          "order": -1,
          "showTitle": true,
          "className": "",
          "visible": "true",
          "disabled": "false"
      },
      {
          "id": "b32a72f75a638968",
          "type": "ui-page",
          "name": "GitHub API",
          "ui": "08bfea67464ffcea",
          "path": "/gh-api",
          "icon": "home",
          "layout": "grid",
          "theme": "3cd9b7f3ad19272d",
          "order": -1,
          "className": "",
          "visible": "true",
          "disabled": "false"
      },
      {
          "id": "08bfea67464ffcea",
          "type": "ui-base",
          "name": "UI Name",
          "path": "/dashboard",
          "includeClientData": true,
          "acceptsClientConfig": [
              "ui-notification",
              "ui-control"
          ]
      },
      {
          "id": "3cd9b7f3ad19272d",
          "type": "ui-theme",
          "name": "Theme Name",
          "colors": {
              "surface": "#ffffff",
              "primary": "#0094ce",
              "bgPage": "#eeeeee",
              "groupBg": "#ffffff",
              "groupOutline": "#cccccc"
          }
      }
  ]
    ```
</details>

### Environment

- Dashboard version: 1.4.0
- Node-RED version: 3.1.0

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

### PR DESCRIPTION
**Pull request by joepavitt**
## Description

Memory overlap occurring because modifications to `msg` _after_ a `msg` was stored in a datastore, still updated the `datastore` entry, even though they're meant to be point in time captures.

## Related Issue(s)

Close #692

### CODE REVIEW

File: nodes/store/data.js [hunk 1]
```diff
@@ -69,13 +69,13 @@ const setters = {
             const filtered = []
             for (const m of msg) {
                 if (canSaveInStore(base, node, m)) {
-                    filtered.push(m)
+                    filtered.push(structuredClone(m))
```
Comment (Steve-Mcl) [inline nodes/store/data.js:72]: `structuredClone` requires NodeJS 17+ 

but dashboard engine specifies `"node": ">=14"`

since we have access to the `RED` object, we should probably use `RED.util.cloneMessage`

```suggestion
                    filtered.push(config.RED.util.cloneMessage(m))
```

File: nodes/store/data.js [hunk 2]
```diff
@@ -69,13 +69,13 @@ const setters = {
...
                 }
             }
             data[node.id] = filtered
         } else {
             if (canSaveInStore(base, node, msg)) {
-                data[node.id] = msg
+                data[node.id] = structuredClone(msg)
```
Comment (Steve-Mcl) [inline nodes/store/data.js:78]:
```suggestion
                data[node.id] = config.RED.util.cloneMessage(msg)
```

Same as above

File: nodes/store/data.js [hunk 3]
```diff
@@ -86,7 +86,7 @@ const setters = {
             if (!data[node.id]) {
                 data[node.id] = []
             }
-            data[node.id].push(msg)
+            data[node.id].push(structuredClone(msg))
```
Comment (Steve-Mcl) [inline nodes/store/data.js:89]:
```suggestion
            data[node.id].push(config.RED.util.cloneMessage(msg))
```

Same as above

**Review by Steve-Mcl — APPROVED** [review]
